ifneq ($(DESTDIR),"")
    IDESTDIR=$(DESTDIR)/
endif


all:
	@true


install:
	mkdir -p $(IDESTDIR)$(IDATADIR)/hashkill/kernels
	-chmod ugo+r $(IDESTDIR)$(IDATADIR)/hashkill/kernels

clean:
	@true


distclean:
	@true

maintainer-clean:
	@true
