LIBS  = 
CFLAGS = -O2 -fpic  -fomit-frame-pointer -minline-all-stringops  -Wall

CC = gcc


# alphabetical order!!!
all: 


install:
	mkdir -p $(IDATADIR)/hashkill/markov
	chmod ugo+r $(IDATADIR)/hashkill/markov
	cp -f *.stat $(IDATADIR)/hashkill/markov

clean:


distclean:
